-- Alwaha-Pro — Supabase Auth + real RLS migration
-- Compatible with the revised index.html supplied with this project.
--
-- IMPORTANT:
-- 1) This script removes the old public.users password storage completely.
-- 2) Passwords are handled only by Supabase Auth (auth.users).
-- 3) Existing custom users from the old bigint public.users table cannot have
--    their plaintext password imported into Auth automatically. Those accounts
--    must sign up again (or be migrated manually by an admin through a secure
--    server-side process).
-- 4) The script does NOT touch auth.users itself and does NOT expose service_role.

begin;
set local lock_timeout = '10s';
set local statement_timeout = '120s';

-- ------------------------------------------------------------
-- 1. Remove old application tables/functions that conflict
-- ------------------------------------------------------------
drop view if exists public.user_directory cascade;
drop function if exists public.is_admin() cascade;
drop function if exists public.handle_new_auth_user() cascade;
drop function if exists public.handle_auth_user_update() cascade;
drop function if exists public.set_updated_at() cascade;

drop table if exists public.game_scores cascade;
drop table if exists public.reels cascade;
drop table if exists public.notifications cascade;
drop table if exists public.verification_requests cascade;
drop table if exists public.friend_requests cascade;
drop table if exists public.messages cascade;
drop table if exists public.comments cascade;
drop table if exists public.products cascade;
drop table if exists public.posts cascade;
drop table if exists public.users cascade;

-- ------------------------------------------------------------
-- 2. Profiles linked 1:1 to Supabase Auth
-- ------------------------------------------------------------
create table public.users (
    id uuid primary key references auth.users(id) on delete cascade,
    first_name text not null default '',
    last_name text not null default '',
    identifier text not null unique,
    phone text not null default '',
    gender text not null default 'ذكر',
    birthdate date,
    avatar_url text,
    is_verified boolean not null default false,
    is_admin boolean not null default false,
    hide_email boolean not null default false,
    hide_phone boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint users_gender_check check (gender in ('ذكر','أنثى'))
);

create index users_identifier_idx on public.users(identifier);
create index users_phone_idx on public.users(phone);
create index users_created_at_idx on public.users(created_at desc);

-- Automatically create a profile whenever Auth creates a user.
create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.users (
        id, first_name, last_name, identifier, phone, gender, birthdate,
        avatar_url, hide_email, hide_phone
    ) values (
        new.id,
        coalesce(new.raw_user_meta_data->>'first_name',''),
        coalesce(new.raw_user_meta_data->>'last_name',''),
        lower(coalesce(new.email,'')),
        coalesce(new.phone,''),
        coalesce(new.raw_user_meta_data->>'gender','ذكر'),
        case
            when coalesce(new.raw_user_meta_data->>'birthdate','') <> ''
            then (new.raw_user_meta_data->>'birthdate')::date
            else null
        end,
        nullif(new.raw_user_meta_data->>'avatar_url',''),
        coalesce((new.raw_user_meta_data->>'hide_email')::boolean,false),
        coalesce((new.raw_user_meta_data->>'hide_phone')::boolean,true)
    )
    on conflict (id) do update set
        identifier = excluded.identifier;
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

-- Keep profile email/phone metadata aligned if Auth changes them.
create or replace function public.handle_auth_user_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    update public.users
    set identifier = lower(coalesce(new.email,'')),
        phone = coalesce(new.phone,''),
        updated_at = now()
    where id = new.id;
    return new;
end;
$$;

drop trigger if exists on_auth_user_updated on auth.users;
create trigger on_auth_user_updated
after update of email, phone on auth.users
for each row execute function public.handle_auth_user_update();

-- ------------------------------------------------------------
-- 3. Home posts
-- ------------------------------------------------------------
create table public.posts (
    id bigint generated by default as identity primary key,
    author_id uuid references auth.users(id) on delete set null,
    author_name text not null default 'مستخدم',
    content text not null,
    post_type text not null default 'عام',
    image_url text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index posts_author_id_idx on public.posts(author_id);
create index posts_created_at_idx on public.posts(created_at desc);

-- ------------------------------------------------------------
-- 4. Marketplace
-- ------------------------------------------------------------
create table public.products (
    id bigint generated by default as identity primary key,
    seller_id uuid not null references auth.users(id) on delete cascade,
    title text not null,
    price text not null,
    category text not null default 'أخرى',
    description text not null,
    image_url text,
    seller_email text not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index products_seller_id_idx on public.products(seller_id);
create index products_created_at_idx on public.products(created_at desc);
create index products_category_idx on public.products(category);

-- ------------------------------------------------------------
-- 5. Persistent comments for posts and reels
-- target_id is text because the current demo reels use values like reel_1.
-- ------------------------------------------------------------
create table public.comments (
    id bigint generated by default as identity primary key,
    target_id text not null,
    target_type text not null default 'post',
    user_id uuid not null references auth.users(id) on delete cascade,
    author_name text not null default 'مستخدم',
    content text not null,
    created_at timestamptz not null default now(),
    constraint comments_target_type_check check (target_type in ('post','reel')),
    constraint comments_content_length check (char_length(content) between 1 and 2000)
);
create index comments_target_idx on public.comments(target_type, target_id, created_at asc);
create index comments_user_id_idx on public.comments(user_id);

-- ------------------------------------------------------------
-- 6. Real direct messages
-- ------------------------------------------------------------
create table public.messages (
    id bigint generated by default as identity primary key,
    sender_id uuid not null references auth.users(id) on delete cascade,
    receiver_id uuid not null references auth.users(id) on delete cascade,
    message text not null,
    created_at timestamptz not null default now(),
    read_at timestamptz,
    constraint messages_not_self check (sender_id <> receiver_id),
    constraint messages_length check (char_length(message) between 1 and 5000)
);
create index messages_sender_receiver_idx on public.messages(sender_id, receiver_id, created_at desc);
create index messages_receiver_sender_idx on public.messages(receiver_id, sender_id, created_at desc);

-- ------------------------------------------------------------
-- 7. Verification requests
-- ------------------------------------------------------------
create table public.verification_requests (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    reason text not null,
    status text not null default 'pending',
    created_at timestamptz not null default now(),
    reviewed_at timestamptz,
    reviewed_by uuid references auth.users(id) on delete set null,
    constraint verification_status_check check (status in ('pending','approved','rejected'))
);
create index verification_requests_user_idx on public.verification_requests(user_id, created_at desc);
create index verification_requests_status_idx on public.verification_requests(status, created_at desc);

-- ------------------------------------------------------------
-- 8. Notifications / friend requests / reels / game scores
-- These are prepared with real ownership fields for later UI wiring.
-- ------------------------------------------------------------
create table public.notifications (
    id bigint generated by default as identity primary key,
    recipient_id uuid not null references auth.users(id) on delete cascade,
    title text not null,
    body text,
    type text not null default 'info',
    is_read boolean not null default false,
    created_at timestamptz not null default now()
);
create index notifications_recipient_idx on public.notifications(recipient_id, created_at desc);

create table public.friend_requests (
    id bigint generated by default as identity primary key,
    requester_id uuid not null references auth.users(id) on delete cascade,
    target_id uuid not null references auth.users(id) on delete cascade,
    status text not null default 'pending',
    created_at timestamptz not null default now(),
    unique(requester_id, target_id),
    constraint friend_requests_not_self check (requester_id <> target_id),
    constraint friend_requests_status_check check (status in ('pending','accepted','rejected','cancelled'))
);

create table public.reels (
    id bigint generated by default as identity primary key,
    author_id uuid references auth.users(id) on delete set null,
    title text,
    author_name text,
    media_url text,
    likes_count bigint not null default 0,
    comments_count bigint not null default 0,
    created_at timestamptz not null default now()
);
create index reels_created_at_idx on public.reels(created_at desc);

create table public.game_scores (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade,
    game_id text not null,
    score bigint not null default 0,
    created_at timestamptz not null default now()
);
create index game_scores_user_idx on public.game_scores(user_id, game_id);
create index game_scores_game_idx on public.game_scores(game_id, score desc);

-- ------------------------------------------------------------
-- 9. Updated-at trigger
-- ------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at before update on public.users for each row execute function public.set_updated_at();
drop trigger if exists posts_set_updated_at on public.posts;
create trigger posts_set_updated_at before update on public.posts for each row execute function public.set_updated_at();
drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at before update on public.products for each row execute function public.set_updated_at();

-- ------------------------------------------------------------
-- 10. Admin helper. Set is_admin=true manually for the owner's profile.
-- ------------------------------------------------------------
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1 from public.users
        where id = auth.uid() and is_admin = true
    );
$$;

-- ------------------------------------------------------------
-- 11. Safe directory view: exposes only fields needed by the user directory.
-- The view never exposes passwords (there is no password column in public.users).
-- ------------------------------------------------------------
drop view if exists public.user_directory cascade;
create view public.user_directory as
select
    id,
    first_name,
    last_name,
    case when hide_email then null else identifier end as identifier,
    case when hide_phone then null else phone end as phone,
    avatar_url,
    is_verified,
    created_at
from public.users;

-- The directory is an intentional security-definer view that exposes only
-- the small set of fields needed by the authenticated user directory.
-- Revoke all default/public access before granting SELECT only to authenticated.
revoke all on table public.user_directory from public, anon, authenticated;

-- ------------------------------------------------------------
-- 12. Grants
-- ------------------------------------------------------------
revoke all on table public.users from anon, authenticated;
revoke all on table public.posts from anon, authenticated;
revoke all on table public.products from anon, authenticated;
revoke all on table public.comments from anon, authenticated;
revoke all on table public.messages from anon, authenticated;
revoke all on table public.verification_requests from anon, authenticated;
revoke all on table public.notifications from anon, authenticated;
revoke all on table public.friend_requests from anon, authenticated;
revoke all on table public.reels from anon, authenticated;
revoke all on table public.game_scores from anon, authenticated;

-- Public feed/market read; authenticated users write according to RLS.
grant select on public.posts, public.products to anon, authenticated;
grant select, insert, update, delete on public.users to authenticated;
grant select, insert, update, delete on public.posts to authenticated;
grant select, insert, update, delete on public.products to authenticated;
grant select, insert, update, delete on public.comments to authenticated;
grant select, insert, update, delete on public.messages to authenticated;
grant select, insert, update on public.verification_requests to authenticated;
grant select, update on public.notifications to authenticated;
grant select, insert, update, delete on public.friend_requests to authenticated;
grant select, insert, update, delete on public.reels to authenticated;
grant select, insert, update, delete on public.game_scores to authenticated;
grant select on public.user_directory to authenticated;

-- ------------------------------------------------------------
-- 13. RLS
-- ------------------------------------------------------------
alter table public.users enable row level security;
alter table public.posts enable row level security;
alter table public.products enable row level security;
alter table public.comments enable row level security;
alter table public.messages enable row level security;
alter table public.verification_requests enable row level security;
alter table public.notifications enable row level security;
alter table public.friend_requests enable row level security;
alter table public.reels enable row level security;
alter table public.game_scores enable row level security;

-- Users: each account can read/update only its own private profile.
create policy users_select_own on public.users for select to authenticated
using ((select auth.uid()) = id);
create policy users_update_own on public.users for update to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);
create policy users_delete_own on public.users for delete to authenticated
using ((select auth.uid()) = id);

-- Posts: public read, authenticated create, owner edit/delete.
create policy posts_select_public on public.posts for select to anon, authenticated using (true);
create policy posts_insert_own on public.posts for insert to authenticated
with check ((select auth.uid()) = author_id);
create policy posts_update_own on public.posts for update to authenticated
using ((select auth.uid()) = author_id)
with check ((select auth.uid()) = author_id);
create policy posts_delete_own on public.posts for delete to authenticated
using ((select auth.uid()) = author_id);

-- Products: public read, owner writes.
create policy products_select_public on public.products for select to anon, authenticated using (true);
create policy products_insert_own on public.products for insert to authenticated
with check ((select auth.uid()) = seller_id);
create policy products_update_own on public.products for update to authenticated
using ((select auth.uid()) = seller_id)
with check ((select auth.uid()) = seller_id);
create policy products_delete_own on public.products for delete to authenticated
using ((select auth.uid()) = seller_id);

-- Comments: public read; authenticated users can create/manage their own.
create policy comments_select_public on public.comments for select to anon, authenticated using (true);
create policy comments_insert_own on public.comments for insert to authenticated
with check ((select auth.uid()) = user_id);
create policy comments_update_own on public.comments for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
create policy comments_delete_own on public.comments for delete to authenticated
using ((select auth.uid()) = user_id);

-- Messages: only the two participants can read; sender creates; receiver can mark read.
create policy messages_select_participant on public.messages for select to authenticated
using ((select auth.uid()) = sender_id or (select auth.uid()) = receiver_id);
create policy messages_insert_sender on public.messages for insert to authenticated
with check ((select auth.uid()) = sender_id);
create policy messages_update_receiver on public.messages for update to authenticated
using ((select auth.uid()) = receiver_id)
with check ((select auth.uid()) = receiver_id);
create policy messages_delete_sender on public.messages for delete to authenticated
using ((select auth.uid()) = sender_id);

-- Verification: owner submits/views; admin reviews.
create policy verification_insert_own on public.verification_requests for insert to authenticated
with check ((select auth.uid()) = user_id);
create policy verification_select_own_or_admin on public.verification_requests for select to authenticated
using ((select auth.uid()) = user_id or public.is_admin());
create policy verification_update_admin on public.verification_requests for update to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Notifications: recipient only.
create policy notifications_select_own on public.notifications for select to authenticated
using ((select auth.uid()) = recipient_id);
create policy notifications_update_own on public.notifications for update to authenticated
using ((select auth.uid()) = recipient_id)
with check ((select auth.uid()) = recipient_id);

-- Friend requests: participants only.
create policy friend_requests_select_participant on public.friend_requests for select to authenticated
using ((select auth.uid()) = requester_id or (select auth.uid()) = target_id);
create policy friend_requests_insert_requester on public.friend_requests for insert to authenticated
with check ((select auth.uid()) = requester_id and requester_id <> target_id);
create policy friend_requests_update_participant on public.friend_requests for update to authenticated
using ((select auth.uid()) = requester_id or (select auth.uid()) = target_id)
with check ((select auth.uid()) = requester_id or (select auth.uid()) = target_id);
create policy friend_requests_delete_requester on public.friend_requests for delete to authenticated
using ((select auth.uid()) = requester_id);

-- Reels: public read, authenticated ownership for mutations.
create policy reels_select_public on public.reels for select to anon, authenticated using (true);
create policy reels_insert_own on public.reels for insert to authenticated
with check ((select auth.uid()) = author_id);
create policy reels_update_own on public.reels for update to authenticated
using ((select auth.uid()) = author_id)
with check ((select auth.uid()) = author_id);
create policy reels_delete_own on public.reels for delete to authenticated
using ((select auth.uid()) = author_id);

-- Scores: public read; users write their own scores.
create policy game_scores_select_public on public.game_scores for select to anon, authenticated using (true);
create policy game_scores_insert_own on public.game_scores for insert to authenticated
with check ((select auth.uid()) = user_id);
create policy game_scores_update_own on public.game_scores for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
create policy game_scores_delete_own on public.game_scores for delete to authenticated
using ((select auth.uid()) = user_id);

-- ------------------------------------------------------------
-- 14. Realtime publication for persistent chat/comments.
-- ------------------------------------------------------------
do $$
begin
    begin alter publication supabase_realtime add table public.messages; exception when duplicate_object then null; end;
    begin alter publication supabase_realtime add table public.comments; exception when duplicate_object then null; end;
end $$;

-- ------------------------------------------------------------
-- 15. Bring any existing Auth users into public.users if profiles are missing.
-- This does not migrate old custom-password accounts.
-- ------------------------------------------------------------
insert into public.users (id, first_name, last_name, identifier, phone)
select
    au.id,
    coalesce(au.raw_user_meta_data->>'first_name',''),
    coalesce(au.raw_user_meta_data->>'last_name',''),
    lower(coalesce(au.email,'')),
    coalesce(au.phone,'')
from auth.users au
where au.email is not null
on conflict (id) do nothing;

commit;

-- AFTER RUNNING THIS SCRIPT:
-- 1) Create/login one account through the revised app.
-- 2) Find its UUID in public.users.
-- 3) If it is the owner/admin account, run ONE manual statement:
--    update public.users set is_admin = true where identifier = 'YOUR-ADMIN-EMAIL';
-- 4) In Supabase Auth settings, configure Site URL + Redirect URLs for the exact
--    deployed web/app URL used by password recovery and email confirmation.
